on: push
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        
        # we use a GitHub action called cache to cache the node modules. 
        # We configure this step to track our package-lock.json for any changes to npm packages and
        # if there is no chance we use the modules from the cache. 
        # This will help us in speeding up the build process.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          cd abb-workspace/
          npm i
          npm run build -- --prod
      - name: update tests coverage
        run: |
          cd abb-workspace/
          npm i -g codecov
          npm run test
          codecov -t {{ secrets.CODECOV_TOKEN }}
      - name: Push Build to Releases
        if: startsWith(github.ref, 'refs/tags/v') 
        uses: ncipollo/release-action@v1
        with:
#           artifacts: "abb-workspace/dist/abb-dumbs-lib"
          token: ${{ secrets.TOKEN }}
